[package]
edition = "2021"
name = "rusty-hass-laptop"
version = "0.1.0"

[dependencies]
battery = "0.7.8"
reqwest = {version = "0.11.6"}
serde = {version = "1.0.130", features = ["derive"]}
serde_json = {version = "1.0"}
